Practicing with Numpy

In [1]:
import numpy as np


In [10]:
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
zero = np.zeros((4,3))
ones = np.ones((3,4))

In [12]:
print(arr1)
print(type(arr1))
print(arr2)
print(type(arr2))
print(zero)
print(ones)

[1 2 3]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
trig = np.array([0,np.pi/2 , np.pi,1])
print(np.sin(trig))

[0.00000000e+00 1.00000000e+00 1.22464680e-16 8.41470985e-01]


In [15]:
val = [("pop",2007,8.9),("top",2006,6.7),("cop",2004,9.2)]
dtype1 = [("name" , "s10") , ("year ",int) , ("gpa",float)]
arr = arr(val.dtype =dtype1)
print(arr)
print(np.sort(arr,order = "name"))


SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (3600990641.py, line 3)